# Generated by Django 6.0.3 on 2026-03-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("intrusion_type", models.CharField(max_length=100)),
                ("risk_score", models.IntegerField()),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
